openejb/arquillian/arquillian-tomee-moviefun-example/src/main/java/org/superbiz/moviefun/MovieController.java
/**
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
package org.superbiz.moviefun;

import org.superbiz.moviefun.util.JsfUtil;
import org.superbiz.moviefun.util.PaginationHelper;

import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import java.io.Serializable;
import java.util.ResourceBundle;

@ManagedBean(name = "movieController")
@SessionScoped
public class MovieController implements Serializable {


    private Movie current;
    private DataModel items = null;
    @EJB
    private Movies ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public MovieController() {
    }

    public Movie getSelected() {
        if (current == null) {
            current = new Movie();
            selectedItemIndex = -1;
        }
        return current;
    }

    private Movies getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Movie) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Movie();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().addMovie(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MovieCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Movie) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().editMovie(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MovieUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Movie) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().deleteMovieId(current.getId());
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("MovieDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.getMovies(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.getMovies(), true);
    }

    @FacesConverter(forClass = Movie.class)
    public static class MovieControllerConverter implements Converter {

        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            MovieController controller = (MovieController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "movieController");
            return controller.ejbFacade.find(getKey(value));
        }

        long getKey(String value) {
            long key;
            key = Long.parseLong(value);
            return key;
        }

        String getStringKey(long value) {
            StringBuffer sb = new StringBuffer();
            sb.append(value);
            return sb.toString();
        }

        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Movie) {
                Movie o = (Movie) object;
                return getStringKey(o.getId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + MovieController.class.getName());
            }
        }

    }

}

openejb/arquillian/arquillian-tomee-moviefun-example/src/main/webapp/movie/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="/template.xhtml">
  <ui:define name="title">
    <h:outputText value="#{bundle.CreateMovieTitle}"></h:outputText>
  </ui:define>
  <ui:define name="body">
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputLabel value="#{bundle.CreateMovieLabel_id}" for="id"/>
        <h:inputText id="id" value="#{movieController.selected.id}" title="#{bundle.CreateMovieTitle_id}"/>
        <h:outputLabel value="#{bundle.CreateMovieLabel_director}" for="director"/>
        <h:inputText id="director" value="#{movieController.selected.director}"
                     title="#{bundle.CreateMovieTitle_director}"/>
        <h:outputLabel value="#{bundle.CreateMovieLabel_title}" for="title"/>
        <h:inputText id="title" value="#{movieController.selected.title}" title="#{bundle.CreateMovieTitle_title}"/>
        <h:outputLabel value="#{bundle.CreateMovieLabel_year}" for="year"/>
        <h:inputText id="year" value="#{movieController.selected.year}" title="#{bundle.CreateMovieTitle_year}"/>
        <h:outputLabel value="#{bundle.CreateMovieLabel_genre}" for="genre"/>
        <h:inputText id="genre" value="#{movieController.selected.genre}" title="#{bundle.CreateMovieTitle_genre}"/>
        <h:outputLabel value="#{bundle.CreateMovieLabel_rating}" for="rating"/>
        <h:inputText id="rating" value="#{movieController.selected.rating}" title="#{bundle.CreateMovieTitle_rating}"/>
      </h:panelGrid>
      <br/>
      <h:commandLink action="#{movieController.create}" value="#{bundle.CreateMovieSaveLink}"/>
      <br/>
      <br/>
      <h:commandLink action="#{movieController.prepareList}" value="#{bundle.CreateMovieShowAllLink}" immediate="true"/>
      <br/>
      <br/>
      <h:commandLink value="#{bundle.CreateMovieIndexLink}" action="/index" immediate="true"/>
    </h:form>
  </ui:define>
</ui:composition>

</html>

openejb/arquillian/arquillian-tomee-moviefun-example/src/main/webapp/movie/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="/template.xhtml">
  <ui:define name="title">
    <h:outputText value="#{bundle.EditMovieTitle}"></h:outputText>
  </ui:define>
  <ui:define name="body">
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputLabel value="#{bundle.EditMovieLabel_id}" for="id"/>
        <h:inputText id="id" value="#{movieController.selected.id}" title="#{bundle.EditMovieTitle_id}"/>
        <h:outputLabel value="#{bundle.EditMovieLabel_director}" for="director"/>
        <h:inputText id="director" value="#{movieController.selected.director}"
                     title="#{bundle.EditMovieTitle_director}"/>
        <h:outputLabel value="#{bundle.EditMovieLabel_title}" for="title"/>
        <h:inputText id="title" value="#{movieController.selected.title}" title="#{bundle.EditMovieTitle_title}"/>
        <h:outputLabel value="#{bundle.EditMovieLabel_year}" for="year"/>
        <h:inputText id="year" value="#{movieController.selected.year}" title="#{bundle.EditMovieTitle_year}"/>
        <h:outputLabel value="#{bundle.EditMovieLabel_genre}" for="genre"/>
        <h:inputText id="genre" value="#{movieController.selected.genre}" title="#{bundle.EditMovieTitle_genre}"/>
        <h:outputLabel value="#{bundle.EditMovieLabel_rating}" for="rating"/>
        <h:inputText id="rating" value="#{movieController.selected.rating}" title="#{bundle.EditMovieTitle_rating}"/>
      </h:panelGrid>
      <h:commandLink action="#{movieController.update}" value="#{bundle.EditMovieSaveLink}"/>
      <br/>
      <br/>
      <h:commandLink action="View" value="#{bundle.EditMovieViewLink}" immediate="true"/>
      <br/>
      <h:commandLink action="#{movieController.prepareList}" value="#{bundle.EditMovieShowAllLink}" immediate="true"/>
      <br/>
      <br/>
      <h:commandLink value="#{bundle.EditMovieIndexLink}" action="/index" immediate="true"/>
    </h:form>
  </ui:define>
</ui:composition>

</html>

openejb/arquillian/arquillian-tomee-moviefun-example/src/main/webapp/movie/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="/template.xhtml">
  <ui:define name="title">
    <h:outputText value="#{bundle.ListMovieTitle}"></h:outputText>
  </ui:define>
  <ui:define name="body">
    <h:form styleClass="jsfcrud_list_form">
      <h:panelGroup id="messagePanel" layout="block">
        <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
      </h:panelGroup>
      <h:outputText escape="false" value="#{bundle.ListMovieEmpty}" rendered="#{movieController.items.rowCount == 0}"/>
      <h:panelGroup rendered="#{movieController.items.rowCount > 0}">
        <h:outputText
                value="#{movieController.pagination.pageFirstItem + 1}..#{movieController.pagination.pageLastItem + 1}/#{movieController.pagination.itemsCount}"/>
        &nbsp;
        <h:commandLink action="#{movieController.previous}"
                       value="#{bundle.Previous} #{movieController.pagination.pageSize}"
                       rendered="#{movieController.pagination.hasPreviousPage}"/>
        &nbsp;
        <h:commandLink action="#{movieController.next}" value="#{bundle.Next} #{movieController.pagination.pageSize}"
                       rendered="#{movieController.pagination.hasNextPage}"/>
        &nbsp;
        <h:dataTable value="#{movieController.items}" var="item" border="0" cellpadding="2" cellspacing="0"
                     rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
          <h:column>
            <f:facet name="header">
              <h:outputText value="#{bundle.ListMovieTitle_id}"/>
            </f:facet>
            <h:outputText value="#{item.id}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="#{bundle.ListMovieTitle_director}"/>
            </f:facet>
            <h:outputText value="#{item.director}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="#{bundle.ListMovieTitle_title}"/>
            </f:facet>
            <h:outputText value="#{item.title}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="#{bundle.ListMovieTitle_year}"/>
            </f:facet>
            <h:outputText value="#{item.year}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="#{bundle.ListMovieTitle_genre}"/>
            </f:facet>
            <h:outputText value="#{item.genre}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="#{bundle.ListMovieTitle_rating}"/>
            </f:facet>
            <h:outputText value="#{item.rating}"/>
          </h:column>
          <h:column>
            <f:facet name="header">
              <h:outputText value="&nbsp;"/>
            </f:facet>
            <h:commandLink action="#{movieController.prepareView}" value="#{bundle.ListMovieViewLink}"/>
            <h:outputText value=" "/>
            <h:commandLink action="#{movieController.prepareEdit}" value="#{bundle.ListMovieEditLink}"/>
            <h:outputText value=" "/>
            <h:commandLink action="#{movieController.destroy}" value="#{bundle.ListMovieDestroyLink}"/>
          </h:column>
        </h:dataTable>
      </h:panelGroup>
      <br/>
      <h:commandLink action="#{movieController.prepareCreate}" value="#{bundle.ListMovieCreateLink}"/>
      <br/>
      <br/>
      <h:commandLink value="#{bundle.ListMovieIndexLink}" action="/index" immediate="true"/>
    </h:form>
  </ui:define>
</ui:composition>

</html>

openejb/arquillian/arquillian-tomee-moviefun-example/src/main/webapp/movie/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core">

<ui:composition template="/template.xhtml">
  <ui:define name="title">
    <h:outputText value="#{bundle.ViewMovieTitle}"></h:outputText>
  </ui:define>
  <ui:define name="body">
    <h:panelGroup id="messagePanel" layout="block">
      <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
    </h:panelGroup>
    <h:form>
      <h:panelGrid columns="2">
        <h:outputText value="#{bundle.ViewMovieLabel_id}"/>
        <h:outputText value="#{movieController.selected.id}" title="#{bundle.ViewMovieTitle_id}"/>
        <h:outputText value="#{bundle.ViewMovieLabel_director}"/>
        <h:outputText value="#{movieController.selected.director}" title="#{bundle.ViewMovieTitle_director}"/>
        <h:outputText value="#{bundle.ViewMovieLabel_title}"/>
        <h:outputText value="#{movieController.selected.title}" title="#{bundle.ViewMovieTitle_title}"/>
        <h:outputText value="#{bundle.ViewMovieLabel_year}"/>
        <h:outputText value="#{movieController.selected.year}" title="#{bundle.ViewMovieTitle_year}"/>
        <h:outputText value="#{bundle.ViewMovieLabel_genre}"/>
        <h:outputText value="#{movieController.selected.genre}" title="#{bundle.ViewMovieTitle_genre}"/>
        <h:outputText value="#{bundle.ViewMovieLabel_rating}"/>
        <h:outputText value="#{movieController.selected.rating}" title="#{bundle.ViewMovieTitle_rating}"/>
      </h:panelGrid>
      <br/>
      <h:commandLink action="#{movieController.destroyAndView}" value="#{bundle.ViewMovieDestroyLink}"/>
      <br/>
      <br/>
      <h:commandLink action="Edit" value="#{bundle.ViewMovieEditLink}"/>
      <br/>
      <h:commandLink action="#{movieController.prepareCreate}" value="#{bundle.ViewMovieCreateLink}"/>
      <br/>
      <h:commandLink action="#{movieController.prepareList}" value="#{bundle.ViewMovieShowAllLink}"/>
      <br/>
      <br/>
      <h:commandLink value="#{bundle.ViewMovieIndexLink}" action="/index" immediate="true"/>

    </h:form>
  </ui:define>
</ui:composition>

</html>